#!/usr/bin/env python3
"""
Setup cron jobs for the 3 portfolio managers.

This script generates the cron entries and crontab configuration.
Run this ON YOUR PI to set up the automated trading cron jobs.

Usage:
    python scripts/portfolios/setup_cron.py          # Show what cron entries would look like
    python scripts/portfolios/setup_cron.py --install  # Actually install the crontab

Prerequisites on your Pi:
1. Python 3.10+ with the direct-indexing project installed
2. Environment variables set for all 3 accounts (see below)
3. Project cloned to ~/direct-indexing or similar

Required environment variables (add to ~/.bashrc or ~/.profile):
    export ALPACA_SP500_API_KEY="your_sp500_key"
    export ALPACA_SP500_API_SECRET="your_sp500_secret"
    export ALPACA_QQQ_API_KEY="your_qqq_key"
    export ALPACA_QQQ_API_SECRET="your_qqq_secret"
    export ALPACA_ALLUS_API_KEY="your_allus_key"
    export ALPACA_ALLUS_API_SECRET="your_allus_secret"

Cron schedule:
    SP500:  Every trading day at 9:25am ET (before market opens at 9:30am)
    QQQ:    Every trading day at 9:26am ET
    All US: Every trading day at 9:27am ET

    Daily status snapshot: Every day at 16:05pm ET (5 min after market close)
    Monthly rebalance: First trading day of each month at 9:20am ET

All times are in New York (ET) timezone.
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
MANAGE_SCRIPT = PROJECT_ROOT / "scripts" / "portfolios" / "manage_portfolio.py"
CRON_LOG_DIR = PROJECT_ROOT / "logs"

# Cron entries (in crontab format)
# Format: "MIN HOUR DAY MONTH DOW COMMAND"
# Using NY time (converted to UTC offsets are approximated; using TZ=America/New_York)


def get_cron_entries() -> list[tuple[str, str]]:
    """Return list of (schedule, command) cron entries."""
    entries = []

    manage_py = str(MANAGE_SCRIPT)

    # ---- SP500: 9:25am ET (pre-market) ----
    # Every weekday (Mon-Fri) at 9:25am New York time
    entries.append((
        "25 9 * * 1-5",
        f"cd {PROJECT_ROOT} && ALPACA_API_KEY=$ALPACA_SP500_API_KEY ALPACA_API_SECRET=$ALPACA_SP500_API_SECRET python3 {manage_py} --index SP500 --execute 2>> {PROJECT_ROOT}/logs/sp500.log"
    ))

    # ---- QQQ: 9:26am ET ----
    entries.append((
        "26 9 * * 1-5",
        f"cd {PROJECT_ROOT} && ALPACA_API_KEY=$ALPACA_QQQ_API_KEY ALPACA_API_SECRET=$ALPACA_QQQ_API_SECRET python3 {manage_py} --index QQQ --execute 2>> {PROJECT_ROOT}/logs/qqq.log"
    ))

    # ---- All US: 9:27am ET ----
    entries.append((
        "27 9 * * 1-5",
        f"cd {PROJECT_ROOT} && ALPACA_API_KEY=$ALPACA_ALLUS_API_KEY ALPACA_API_SECRET=$ALPACA_ALLUS_API_SECRET python3 {manage_py} --index ALL_US --execute 2>> {PROJECT_ROOT}/logs/allus.log"
    ))

    # ---- Daily status snapshot: 4:05pm ET (5 min after close) ----
    entries.append((
        "5 16 * * 1-5",
        f"cd {PROJECT_ROOT} && ALPACA_API_KEY=$ALPACA_SP500_API_KEY ALPACA_API_SECRET=$ALPACA_SP500_API_SECRET python3 {manage_py} --index SP500 --status 2>> {PROJECT_ROOT}/logs/sp500_status.log"
    ))
    entries.append((
        "6 16 * * 1-5",
        f"cd {PROJECT_ROOT} && ALPACA_API_KEY=$ALPACA_QQQ_API_KEY ALPACA_API_SECRET=$ALPACA_QQQ_API_SECRET python3 {manage_py} --index QQQ --status 2>> {PROJECT_ROOT}/logs/qqq_status.log"
    ))
    entries.append((
        "7 16 * * 1-5",
        f"cd {PROJECT_ROOT} && ALPACA_API_KEY=$ALPACA_ALLUS_API_KEY ALPACA_API_SECRET=$ALPACA_ALLUS_API_SECRET python3 {manage_py} --index ALL_US --status 2>> {PROJECT_ROOT}/logs/allus_status.log"
    ))

    # ---- Monthly rebalance: First weekday of month at 9:20am ET ----
    # Day 1-7 of month, weekday only (1-5), at 9:20am
    # Cron: 0 9 1-7 * 1-5 (runs at 9am on first 7 days of month, only weekdays)
    entries.append((
        "20 9 1-7 * 1-5",
        f"cd {PROJECT_ROOT} && ALPACA_API_KEY=$ALPACA_SP500_API_KEY ALPACA_API_SECRET=$ALPACA_SP500_API_SECRET python3 {manage_py} --index SP500 --rebalance --execute 2>> {PROJECT_ROOT}/logs/sp500_rebal.log"
    ))
    entries.append((
        "21 9 1-7 * 1-5",
        f"cd {PROJECT_ROOT} && ALPACA_API_KEY=$ALPACA_QQQ_API_KEY ALPACA_API_SECRET=$ALPACA_QQQ_API_SECRET python3 {manage_py} --index QQQ --rebalance --execute 2>> {PROJECT_ROOT}/logs/qqq_rebal.log"
    ))
    entries.append((
        "22 9 1-7 * 1-5",
        f"cd {PROJECT_ROOT} && ALPACA_API_KEY=$ALPACA_ALLUS_API_KEY ALPACA_API_SECRET=$ALPACA_ALLUS_API_SECRET python3 {manage_py} --index ALL_US --rebalance --execute 2>> {PROJECT_ROOT}/logs/allus_rebal.log"
    ))

    return entries


def generate_crontab() -> str:
    """Generate the complete crontab content."""
    lines = [
        "# Direct Indexing - Automated Portfolio Management",
        "# Generated by scripts/portfolios/setup_cron.py",
        "# ",
        "# Prerequisites:",
        "#   1. Set environment variables in ~/.bashrc:",
        "#        export ALPACA_SP500_API_KEY=...",
        "#        export ALPACA_SP500_API_SECRET=...",
        "#        export ALPACA_QQQ_API_KEY=...",
        "#        export ALPACA_QQQ_API_SECRET=...",
        "#        export ALPACA_ALLUS_API_KEY=...",
        "#        export ALPACA_ALLUS_API_SECRET=...",
        "#   2. Create log directory: mkdir -p ~/direct-indexing/logs",
        "#   3. Install: python3 scripts/portfolios/setup_cron.py --install",
        "",
        "# Set timezone to New York",
        "TZ=America/New_York",
        "",
        "# === MARKET HOURS (9:30am - 4:00pm ET, Mon-Fri) ===",
        "#",
        "# Pre-market deploy (25-27 min): SP500, QQQ, All US at 9:25-27am",
        "# Market close status: 4:05-7pm (5 min after 4pm close)",
        "# Monthly rebalance: 9:20-22am on first weekdays of month",
        "",
    ]

    for schedule, command in get_cron_entries():
        lines.append(f"{schedule} {command}")

    return "\n".join(lines)


def show_crontab() -> None:
    """Print the generated crontab."""
    print("=" * 70)
    print("GENERATED CRONTAB")
    print("=" * 70)
    print(generate_crontab())
    print("=" * 70)


def install_crontab() -> None:
    """Install the crontab."""
    crontab = generate_crontab()

    # Create log directory
    CRON_LOG_DIR.mkdir(parents=True, exist_ok=True)

    print("Installing crontab...")

    # Write to crontab
    result = subprocess.run(
        ["crontab", "-"],
        input=crontab.encode(),
        capture_output=True,
    )

    if result.returncode == 0:
        print("✓ Crontab installed successfully!")
        print("\nCurrent crontab:")
        result = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
        print(result.stdout)
    else:
        print(f"✗ Failed to install crontab: {result.stderr.decode()}")
        sys.exit(1)


def main() -> int:
    parser = argparse.ArgumentParser(description="Setup cron jobs for portfolio management")
    parser.add_argument("--install", action="store_true",
                        help="Actually install the crontab (default: just show it)")
    args = parser.parse_args()

    # Verify the manage_portfolio.py script exists
    if not MANAGE_SCRIPT.exists():
        print(f"ERROR: {MANAGE_SCRIPT} not found!")
        print(f"  Make sure you're running from the project directory on your Pi.")
        return 1

    # Check environment variables
    missing = []
    for key in ["ALPACA_SP500_API_KEY", "ALPACA_SP500_API_SECRET",
                "ALPACA_QQQ_API_KEY", "ALPACA_QQQ_API_SECRET",
                "ALPACA_ALLUS_API_KEY", "ALPACA_ALLUS_API_SECRET"]:
        if not os.environ.get(key):
            missing.append(key)

    if missing:
        print(f"WARNING: The following environment variables are not set:")
        for k in missing:
            print(f"  {k}")
        print("\nSet them in ~/.bashrc before running --install")
        print()

    if args.install:
        install_crontab()
    else:
        show_crontab()
        print("\nTo install, run: python3 scripts/portfolios/setup_cron.py --install")
        print("Make sure to set all ALPACA_* environment variables first.")

    return 0


if __name__ == "__main__":
    sys.exit(main())